name: Claude Code (on @claude comment)

on:
  issue_comment:
    types: [created]


permissions:
  id-token: write       # OIDC token için şart
  contents: write
  pull-requests: write

jobs:
  run:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}   # opsiyonel ama önerilir
          mode: implement
          issue_number: ${{ github.event.issue.number }}
          open_pull_request: true
          include_paths: |
            index.html
            test.html
