name: Claude Code (on @claude comment)

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write  # action'ın issue'a yorum/bağlantı yazabilmesi için

jobs:
  run:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ github.token }}
          trigger_phrase: '@claude'
          base_branch: master
          branch_prefix: auto/claude-
          prompt: |
            Use the linked issue as the primary spec.
            Modify only: index.html, test.html.
            Keep changes minimal and open a PR when done.

          claude_args: "--max-turns 3"
